// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Dima",
            "url": "http://t.me/BelozerovD"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/scan/domain": {
            "get": {
                "description": "Эндпоинт для проверки домена и определения его цвета на основе зоны риска",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domain"
                ],
                "summary": "Проверка домена через Kaspersky API",
                "operationId": "domain-check",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Домен для проверки",
                        "name": "request",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная проверка домена. Возможные значения цвета: Red, Green, Grey.",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseToClient"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос или ошибка в параметрах"
                    },
                    "404": {
                        "description": "Результаты поиска не найдены"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ResponseToClient": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Minions API",
	Description:      "API server for Minions.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
