definitions:
  models.ResponseToClient:
    properties:
      color:
        type: string
    type: object
info:
  contact:
    name: Dima
    url: http://t.me/BelozerovD
  description: API server for Minions.
  title: Minions API
paths:
  /api/scan/domain:
    get:
      consumes:
      - application/json
      description: Эндпоинт для проверки домена и определения его цвета на основе
        зоны риска
      operationId: domain-check
      parameters:
      - description: Домен для проверки
        in: query
        name: request
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Успешная проверка домена. Возможные значения цвета: Red, Green,
            Grey.'
          schema:
            $ref: '#/definitions/models.ResponseToClient'
        "400":
          description: Некорректный запрос или ошибка в параметрах
        "404":
          description: Результаты поиска не найдены
        "500":
          description: Внутренняя ошибка сервера
      summary: Проверка домена через Kaspersky API
      tags:
      - Domain
swagger: "2.0"
